twig:
    default_path: '%kernel.project_dir%/templates'
    #cela permet d'ajouter un template bootsrap  sur nos forms
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
